# Generated by Django 3.1.7 on 2021-03-31 12:58

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Students', '0001_initial'),
        ('Sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_title', models.CharField(blank=True, max_length=20)),
                ('task_description', models.CharField(blank=True, max_length=100, null=True)),
                ('task_dateDue', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('task_dueTime', models.TimeField(blank=True, null=True)),
                ('task_dateCreated', models.DateField(default=datetime.date.today)),
                ('task_totalScore', models.IntegerField(blank=True, default=0, null=True)),
                ('task_file', models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('sessions', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Sessions.session')),
            ],
            options={
                'db_table': 'Tasks',
            },
        ),
        migrations.CreateModel(
            name='Student_Session_Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback', models.CharField(default='No Feedback', max_length=300)),
                ('file', models.FileField(blank=True, null=True, upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('actualScore', models.IntegerField(default=0, null=True)),
                ('isSubmitted', models.BooleanField(default=False)),
                ('isGraded', models.BooleanField(default=False)),
                ('dateSubmitted', models.DateField(default=datetime.date.today)),
                ('session', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Sessions.session')),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Students.student')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tasks.tasks')),
            ],
            options={
                'db_table': 'Student_Session_Task',
            },
        ),
    ]
