# Generated by Django 3.1.7 on 2021-03-28 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0001_initial'),
        ('Tasks', '0004_auto_20210328_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_session_task',
            name='session',
        ),
        migrations.AddField(
            model_name='student_session_task',
            name='student',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Students.student'),
        ),
    ]
