# Generated by Django 3.1.7 on 2021-03-28 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Sessions', '0001_initial'),
        ('Tasks', '0005_auto_20210328_0859'),
    ]

    operations = [
        migrations.AddField(
            model_name='student_session_task',
            name='session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Sessions.session'),
        ),
    ]
