# Generated by Django 3.1.7 on 2021-03-21 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
