# Generated by Django 3.1.7 on 2021-03-21 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0003_auto_20210321_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.CharField(default='placeholder.png', max_length=100),
        ),
    ]
