# Generated by Django 3.1.7 on 2021-03-27 01:21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Interest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('activity_id', models.AutoField(primary_key=True, serialize=False)),
                ('act_name', models.CharField(max_length=20, unique=True)),
                ('act_description', models.CharField(max_length=300)),
                ('act_photo', models.FileField(default='default.png', upload_to='')),
                ('act_venue', models.CharField(max_length=50)),
                ('act_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'Activity',
            },
        ),
        migrations.CreateModel(
            name='Activity_Interest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Activity.activity')),
                ('interest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Interest.interest')),
            ],
            options={
                'db_table': 'Activity_Interest',
                'unique_together': {('interest', 'activity')},
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='interests',
            field=models.ManyToManyField(blank=True, through='Activity.Activity_Interest', to='Interest.Interest'),
        ),
    ]
