# Generated by Django 3.1.7 on 2021-03-21 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interest', '0002_auto_20210321_1108'),
        ('Activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='act_name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='interests',
            field=models.ManyToManyField(null=True, through='Activity.Activity_Interest', to='Interest.Interest'),
        ),
    ]
