# Generated by Django 3.1.7 on 2021-03-21 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activity', '0003_auto_20210321_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='act_description',
            field=models.CharField(max_length=300),
        ),
    ]
