# Generated by Django 3.1.7 on 2021-03-21 07:11

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Modules', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modules',
            name='files',
        ),
        migrations.AlterModelTable(
            name='modules',
            table=None,
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('modules', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Modules.modules')),
            ],
            options={
                'db_table': 'modules',
            },
        ),
    ]
