# Generated by Django 3.1.7 on 2021-03-21 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Modules', '0002_auto_20210321_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modules',
            old_name='filename',
            new_name='modulename',
        ),
    ]
