# Generated by Django 3.1.7 on 2021-03-21 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Modules', '0003_auto_20210321_1538'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Files',
        ),
        migrations.DeleteModel(
            name='Modules',
        ),
    ]
