# Generated by Django 3.1.7 on 2021-03-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interest',
            fields=[
                ('interest_id', models.AutoField(primary_key=True, serialize=False)),
                ('int_name', models.CharField(max_length=20)),
                ('int_description', models.CharField(max_length=100)),
                ('int_photo', models.FileField(default='default.png', upload_to='')),
            ],
            options={
                'db_table': 'Interest',
            },
        ),
    ]
