# Generated by Django 3.1.7 on 2021-03-21 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interest', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='int_name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
