# Generated by Django 3.1.7 on 2021-03-21 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0001_initial'),
        ('Interest', '0002_auto_20210321_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='interest',
            name='int_students',
            field=models.ManyToManyField(to='Students.Student'),
        ),
    ]
