# Generated by Django 3.1.7 on 2021-03-21 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Interest', '0003_interest_int_students'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interest',
            old_name='int_students',
            new_name='students',
        ),
    ]
