# Generated by Django 3.1.7 on 2021-03-21 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Students', '0001_initial'),
        ('Interest', '0004_auto_20210321_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='students',
            field=models.ManyToManyField(blank=True, to='Students.Student'),
        ),
    ]
