# Generated by Django 3.1.7 on 2021-03-29 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('session_code', models.CharField(max_length=20)),
                ('session_name', models.CharField(max_length=50)),
                ('students', models.ManyToManyField(blank=True, to='Students.Student')),
            ],
            options={
                'db_table': 'Session',
            },
        ),
    ]
