# Generated by Django 3.1.7 on 2021-03-21 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('session_id', models.AutoField(primary_key=True, serialize=False)),
                ('session_code', models.CharField(max_length=20)),
                ('session_name', models.CharField(max_length=50)),
                ('session_students', models.ManyToManyField(to='Students.Student')),
            ],
            options={
                'db_table': 'Session',
            },
        ),
        migrations.CreateModel(
            name='Student_Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session', models.ForeignKey(db_column='session_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Sessions.session')),
                ('student', models.ForeignKey(db_column='student_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Students.student')),
            ],
            options={
                'db_table': 'Student_Session',
            },
        ),
    ]
