# Generated by Django 3.1.7 on 2021-03-21 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sessions', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student_Session',
        ),
    ]
