# Generated by Django 3.1.7 on 2021-03-21 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sessions', '0002_delete_student_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='session',
            old_name='session_students',
            new_name='students',
        ),
    ]
